#
# For Iosevka-27.3
#

[buildPlans.iosevka-u5i5]
family = "iosevka-u5i5"
spacing = "term"
serifs = "slab"
no-cv-ss = true
export-glyph-names = true

[buildPlans.iosevka-u5i5.variants]
inherits = "ss20"

[buildPlans.iosevka-u5i5.variants.design]
capital-b = "more-asymmetric-interrupted-bilateral-serifed"
capital-d = "more-rounded-bilateral-serifed"
capital-j = "descending-serifed-both-sides"
capital-m = "slanted-sides-hanging-serifed"
capital-q = "crossing-curly-tailed"
capital-r = "curly-open-serifed"
g = "double-storey-open"
i = "serifed-semi-tailed"
l = "serifed-semi-tailed"
m = "short-leg-serifed"
#zero = "oval-dotted"
zero = "oval-top-right-cutout"
one = "base-long-top-serif"
seven = "bend-serifed"
eight = "crossing-asymmetric"
tilde = "high"
ampersand = "upper-open"
dollar = "open"
percent = "rings-continuous-slash"
bar = "force-upright"
question = "corner"

[buildPlans.iosevka-u5i5.variants.italic]
m = "short-leg-top-left-and-bottom-right-serifed"
v = "cursive-serifed"
w = "cursive-serifed"
x = "chancery"
z = "cursive"

[buildPlans.iosevka-u5i5.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-u5i5.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-u5i5.widths.normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.iosevka-u5i5.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-u5i5.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

